### ISSUE TITLE
Update of the default directory 

### ISSUE THREAD

**Issue by chaouiya** [archimede-institut/GINsim#14]
When opening  an existing model from the starting GINsim window, the "Save As" and "Open" options of the File menu locate the default directory to the one of the last saved model, which is not necessarily that of the current model. 

For example, I work on a model A.zginml and I save it in a directory dir1. If now I use the option Open of the File menu, the default directory is dir1 (that's OK)
But if I close model A.zginml and I open a model B.zginml listed in the GINsim  starting window, which is in a directory dir2, the defaults directory is still dir1.

This does not happen if I open B.zginml using the Open button of the starting GINsim window.

**Comment by olivierChabrol** [comment]
create settings widows

**Comment by olivierChabrol** [comment]
based on file $HOME/.config/org.ginsim.xml
with the entry <option key="gui.last_working_directory" type="string" value="/home/user/GINsim/data"/>
 thinking about make FileSelectionHelper as an singleton instead of a static class with static methods
