### ISSUE TITLE
Correction of bug Component Name vs Id

### ISSUE THREAD

**Issue by dbenielli** [archimede-institut/GINsim#3]
1) identification of the components in the window for the « Run simulation » and « Assess attractor
reachability » settings
each model component has an Id (in principle a short name) and a Name (possibly extended name)
here in the model, I've added a name to p53 (« foo ») and this is what appears in the window to set
the simulation parameters. This should not be the case (For the remaining components, the Id is
displayed because they have no Name). I checked that in the window displaying the stable states,
the sole Id is used, same in all other windows (perturbation setting, display of STG, HTG, stable
states, window displaying the STG, etc.) The only window that has the same issue is that of
The Id should be used for all the components in these 2 windows

**Comment by chaouiya** [comment]
Done!!

**Comment by dbenielli** [comment]
Be testeed and approuved
