### ISSUE TITLE
Weird message "Quit GINsim?" appearing in the main GINsim window

### ISSUE THREAD

**Issue by chaouiya** [archimede-institut/GINsim#5]
When closing a model, we return to the main window, and the message "Quit GINsim?" appears on the upper right part. This should not be the case (we have a button to quit). See attached screenshot
![Screenshot from 2024-10-30 19-28-29](https://github.com/user-attachments/assets/040f37e0-5675-4851-96ce-e9c8ce67a619)

**Comment by dbenielli** [comment]
For now I did not manage to reproduce this bug, I will test again

**Comment by chaouiya** [comment]
Open a model, then close it (through the File menu ot crtl-w)
